version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "5000:5000"  # Map port 3000 on host to port 80 in the container (Nginx default)
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # Required for MySQL
      MYSQL_DATABASE: contact
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql  # Correct volume syntax
    ports:
      - "5000:5000"  # Expose MySQL port (optional)

volumes:
  db_data:  # Declare the named volume